// Ở đây bạn có thể lấy dữ liệu menu từ API hoặc viết cứng, ví dụ minh họa cách viết này
export default [
  {
    id: 10000,
    documentId: "zh92qt1mxkxtky8cvozt1ke7l",
    title: "详情页",
    localesKey: null,
    file: "/src/app/views/tabs/detail.vue",
    path: "/tabs/detail/:id",
    name: "tabs/detail",
    icon: "ReceiptOutline",
    hasClose: false,
    sort: "0",
    hasMenu: true,
    hasRouter: false,
    hasTab: false,
    root: null,
    keepAlive: false,
    overlayRouting: false,
    pid: "ctk3vsnxfv7dyaf0awz587uz",
    extra: null,
    embed: null,
  },
  {
    id: 10001,
    documentId: "zh92qt1mopxtky8cvozt1ke7l",
    title: "详情页",
    localesKey: null,
    file: "/src/app/views/business/index.vue",
    path: "/business",
    name: "business",
    icon: "ReceiptOutline",
    hasClose: false,
    sort: "0",
    hasMenu: true,
    hasRouter: false,
    hasTab: false,
    root: "/",
    keepAlive: false,
    overlayRouting: false,
    pid: "",
    embed: null,
  },
];
